use_frameworks!

platform :ios, '9.0'

target 'MyCustomLib_Example' do
  pod 'MyCustomLib', :path => '../'

  target 'MyCustomLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
